### ISSUE TITLE
Excess "Password Protected " windows pops-up when software was relaunched from minimized.

### ISSUE THREAD

**Issue by kaio** [bendikro/deluge#3]
Procedures: 
1. install deluge
2. turn on System Tray Protected Password option in settings 
3. turn on Close will minimize to tray option in settings 
4. minimize main window to tray. 
5. launch software via icon or tray icon 
6. observe results 

Expect results:
Password Protected window pops up once no matter how many times it was launched.

Observed results:
a new instance of such window pops up, every time the software was launched. And once a correct password was inputted, the main window opens but the excess Password Protected windows are still remained.

(dev comment: a new Password Protected window should be created when there was no such window present. A 'if' condition should be added to check before creating a new instance. i.e. Singleton Pattern?)

**Comment by bendikro** [comment]
Created trac ticket: http://dev.deluge-torrent.org/ticket/2788#ticket
