### ISSUE TITLE
Add Torrent window too high for netbook displays (1024x600) on Gnome 3.14

### ISSUE THREAD

**Issue by johnchristopher** [bendikro/deluge#4]
The Add Torrent window does not fit vertically on a 1024x600 screen in GNOME 3.14 with default gnome configuration (one bar on top). The buttons on the bottom edge are off screen. This happens always, no matter if you add one or more torrents.
Hitting the `enter` key doesn't work either (though tabbing through the controls might work, I haven't tried).

Seems to be a regression from http://dev.deluge-torrent.org/ticket/518.

edit: deluge 1.3.10 (default Debian 8 package)

![capture d ecran de 2016-03-14 20_22_43](https://cloud.githubusercontent.com/assets/3525434/13757168/7afad614-ea23-11e5-8fec-edfeaf26b266.png)

![capture d ecran de 2016-03-14 20_22_51](https://cloud.githubusercontent.com/assets/3525434/13757176/87206dd2-ea23-11e5-94bf-70a91d0dab70.png)

**Comment by bendikro** [comment]
Created ticket on deluge trac: http://dev.deluge-torrent.org/ticket/2795
